"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import re

def str_to_bool(val):
    val = str(val).strip().lower()
    return val in ('true', '1', 'yes')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOT_ENV_PATH = BASE_DIR / ".env"

if DOT_ENV_PATH.exists():
    load_dotenv(DOT_ENV_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', os.environ.get('SECRET_KEY', 'django-insecure-xq1rhglk0+4r@x9=sqv*ah7@d#5yq_v1md!0rzsrh2^+u+xyaw'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str_to_bool(os.environ.get('DEBUG', 'False'))

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError('Set a real SECRET_KEY in production (DJANGO_SECRET_KEY env var not set or still using insecure default)')

CUSTOM_DOMAIN = os.environ.get('CUSTOM_DOMAIN', os.environ.get('DOMAIN', ''))
_custom_host = CUSTOM_DOMAIN.split(':')[0] if CUSTOM_DOMAIN else ''

# basic  — no reverse proxy; frontend :3000, backend :8000, plain HTTP
# proxy  — behind Traefik or Nginx; HTTPS, no ports in URLs
DEPLOYMENT_MODE = os.environ.get('DEPLOYMENT_MODE', 'proxy')
BASIC_MODE = DEPLOYMENT_MODE == 'basic'

raw_hosts = os.environ.get('ALLOWED_HOSTS', '')

_base_hosts = ['127.0.0.1', 'localhost', '0.0.0.0', 'django', 'backend', 'siene-backend', 'host.docker.internal']
if _custom_host:
    _base_hosts.append(_custom_host)

if raw_hosts.strip():
    ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(',') if h.strip()] + _base_hosts
else:
    ALLOWED_HOSTS = _base_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'ninja',
    'ninja_extra',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
    'allauth.mfa',
    'corsheaders',

    # Celery results + periodic task schedule
    'django_celery_beat',
    'django_celery_results',

    'users',
    'registry',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

SITE_ID = 1

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.oidc_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use SQLite only when explicitly requested (USE_SQLITE=1) or when no DB_HOST
# is configured.  In Docker Compose DB_HOST is always set, so PostgreSQL is
# used automatically there.  On the dev host you can keep SQLite by either
# setting USE_SQLITE=1 or simply not setting DB_HOST.
_use_sqlite = str_to_bool(os.environ.get('USE_SQLITE', '0')) or not os.environ.get('DB_HOST', '')

if _use_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'siene'),
            'USER': os.environ.get('DB_USER', 'siene'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            # Re-validate the connection before reuse so stale sockets after a
            # Postgres restart / RDS failover don't surface as OperationalErrors.
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOW_CREDENTIALS = True

if CUSTOM_DOMAIN:
    _escaped = re.escape(CUSTOM_DOMAIN)
    if BASIC_MODE:
        # No reverse proxy — frontend on :3000, backend on :8000, plain HTTP.
        CORS_ALLOWED_ORIGIN_REGEXES = [
            rf"^http://[a-z0-9-]+\.{_escaped}(:[0-9]+)?$",
            rf"^http://{_escaped}(:[0-9]+)?$",
        ]
        CSRF_TRUSTED_ORIGINS = [
            f'http://{CUSTOM_DOMAIN}',
            f'http://{CUSTOM_DOMAIN}:3000',
            f'http://{CUSTOM_DOMAIN}:8000',
        ]
    else:
        # Behind a reverse proxy (Traefik / Nginx) — HTTPS only.
        CORS_ALLOWED_ORIGIN_REGEXES = [
            rf"^https://[a-z0-9-]+\.{_escaped}(:[0-9]+)?$",
            rf"^https://{_escaped}(:[0-9]+)?$",
        ]
        CSRF_TRUSTED_ORIGINS = [
            f'https://{CUSTOM_DOMAIN}',
            f'https://{CUSTOM_DOMAIN}:3000',
        ]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

# Session Cookie Configuration for Cross-Domain Auth
# Only set a cookie domain when CUSTOM_DOMAIN is provided — setting it to an
# empty string or bare '.' breaks cookies entirely.
SESSION_COOKIE_DOMAIN = f'.{CUSTOM_DOMAIN.split(":")[0]}' if CUSTOM_DOMAIN and not BASIC_MODE else None
SESSION_COOKIE_SAMESITE = 'Lax'
# Only mark cookies Secure when actually running over HTTPS. Controlled
# explicitly via env var so it works correctly regardless of DEBUG.
SESSION_COOKIE_SECURE = str_to_bool(os.environ.get('SESSION_COOKIE_SECURE', '0'))
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_LOGOUT_ON_GET = False  # require POST to prevent CSRF-triggered logout via GET
LOGIN_REDIRECT_URL = "/accounts/auth/gate/"
LOGIN_URL = '/accounts/login/'
ACCOUNT_SIGNUP_REDIRECT_URL = "/accounts/auth/gate/"
ACCOUNT_SIGNUP_ENABLED = str_to_bool(os.environ.get('ACCOUNT_ALLOW_SIGNUPS', 'True'))
ACCOUNT_ADAPTER = 'users.adapters.MyAccountAdapter'
APP_NAME = os.environ.get('APP_NAME', 'Example Name')

# OIDC/Social Account Configuration
# Configure via environment variables:
#   OIDC_PROVIDER_ID: A slug identifying your provider (used in the callback URL)
#   OIDC_CLIENT_ID: Client ID from your OIDC provider
#   OIDC_CLIENT_SECRET: Client secret from your OIDC provider
#   OIDC_SERVER_URL: Full URL to the .well-known/openid-configuration endpoint

OIDC_PROVIDER_TYPE = os.environ.get('OIDC_PROVIDER_ID', os.environ.get('OIDC_PROVIDER_TYPE', '')).lower()
OIDC_CLIENT_ID = os.environ.get('OIDC_CLIENT_ID', '')
OIDC_CLIENT_SECRET = os.environ.get('OIDC_CLIENT_SECRET', '')
OIDC_SERVER_URL = os.environ.get('OIDC_SERVER_URL', '')

OIDC_ENABLED = bool(OIDC_PROVIDER_TYPE and OIDC_CLIENT_ID and OIDC_CLIENT_SECRET and OIDC_SERVER_URL)

OIDC_APPS = []
if OIDC_ENABLED:
    OIDC_APPS = [
        {
            "provider_id": OIDC_PROVIDER_TYPE,
            "name": "SSO",
            "client_id": OIDC_CLIENT_ID,
            "secret": OIDC_CLIENT_SECRET,
            "settings": {
                "server_url": OIDC_SERVER_URL
            }
        }
    ]

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": OIDC_APPS
    }
}

# if OIDC_PROVIDER_TYPE is not '' or OIDC_PROVIDER_TYPE is not None:
#     SOCIALACCOUNT_ONLY = True
# else:
#     SOCIALACCOUNT_ONLY = False

# Social Account Settings - Enable Email-Based Account Linking
SOCIALACCOUNT_ADAPTER = 'users.adapters.MySocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True  # Allow automatic signup via social login
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'  # Don't force email verification for social accounts
SOCIALACCOUNT_QUERY_EMAIL = True  # Enable querying email from social provider
SOCIALACCOUNT_EMAIL_AUTHENTICATION=True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT=True

# Email Configuration
# EMAIL_ENABLED=1  → use SMTP (requires EMAIL_HOST_USER + EMAIL_HOST_PASSWORD)
# EMAIL_ENABLED=0  → discard all outgoing email silently (default in dev,
#                    also safe for production installs that don't need email)
_email_enabled = str_to_bool(os.environ.get('EMAIL_ENABLED', '0'))

if DEBUG or not _email_enabled:
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = str_to_bool(os.environ.get('EMAIL_USE_TLS', '1'))
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Siene <noreply@example.com>')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SSL / cookie security — all default to off so plain HTTP works out of the box.
# Set to 1 in production when running behind an HTTPS reverse proxy.
SECURE_SSL_REDIRECT = str_to_bool(os.environ.get('SECURE_SSL_REDIRECT', '0'))
CSRF_COOKIE_SECURE = str_to_bool(os.environ.get('CSRF_COOKIE_SECURE', '0'))

if not DEBUG:
    # HSTS (HTTP Strict Transport Security) — only meaningful with HTTPS
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = str_to_bool(os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', '0'))
    SECURE_HSTS_PRELOAD = str_to_bool(os.environ.get('SECURE_HSTS_PRELOAD', '0'))

    # Proxy SSL Header (for reverse proxy setups like Nginx/Traefik/Caddy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_REFERRER_POLICY = 'same-origin'

# regardless of DEBUG mode — needed when Traefik/nginx terminates TLS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Celery ────────────────────────────────────────────────────────────────────

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Prefetch 1 message at a time (default is 4).  With the scans worker running at
# concurrency 1 this means only the single executing task is held in-memory —
# the queue is not pre-drained into the worker process.  Combined with acks_late,
# a crash or OOM-kill will cause the broker to redeliver the unacknowledged task
# rather than silently losing it.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Acknowledge the task only after it completes (or fails permanently), not at
# the moment the worker picks it up.  This ensures that if the worker is
# OOM-killed mid-scan the task requeues automatically instead of staying stuck
# in 'pending'/'running' forever and requiring manual reset-stale intervention.
CELERY_TASK_ACKS_LATE = True

# Route tasks to their queues by module prefix
CELERY_TASK_ROUTES = {
    'registry.tasks.run_vulnerability_scan': {'queue': 'scans'},
    'registry.tasks.run_secret_scan':        {'queue': 'scans'},
    'registry.tasks.run_misconfig_scan':     {'queue': 'scans'},
    # Combined on-push scan — downloads image once, runs all enabled scan types
    'registry.tasks.run_combined_scan':      {'queue': 'scans'},
    # run_trivy_db_update writes to the shared trivy_cache volume — it must run
    # in siene-worker-scans, the only container that mounts that volume.
    'registry.tasks.run_trivy_db_update':    {'queue': 'scans'},
    'registry.tasks.run_sbom':               {'queue': 'sbom'},
    'registry.tasks.run_replication':        {'queue': 'default'},
    'registry.tasks.run_gc':                 {'queue': 'default'},
    'registry.tasks.run_registry_sync':      {'queue': 'default'},
    # Webhook event processing — runs in default worker, not scan worker
    'registry.tasks.process_registry_events': {'queue': 'default'},
    # Orchestrator only — dispatches to 'scans' but must not block the scan worker itself
    'registry.tasks.run_rescan_stale':       {'queue': 'default'},
}

CELERY_RESULT_EXTENDED = True

# Celery Beat — periodic task schedule
# run_gc fires every hour; the task itself checks whether the configured
# interval has elapsed before doing any real work.
from celery.schedules import crontab  # noqa: E402
CELERY_BEAT_SCHEDULE = {
    'gc-hourly': {
        'task': 'registry.tasks.run_gc',
        'schedule': crontab(minute=0),   # top of every hour
        'kwargs': {'force': False},
    },
    'rescan-stale-images': {
        # Re-scan all tags whose most recent vuln scan is older than 24 h,
        # so new CVEs are picked up without requiring a re-push.
        'task': 'registry.tasks.run_rescan_stale',
        'schedule': crontab(minute=30, hour='*/6'),  # every 6 h at :30
    },
    'trivy-db-update': {
        # Fires every hour; the task itself gates on the configured interval
        # and whether auto-update is enabled, matching the run_gc pattern.
        'task': 'registry.tasks.run_trivy_db_update',
        'schedule': crontab(minute=15),  # :15 past every hour
        'kwargs': {'force': False},
    },
}

# ── External services ─────────────────────────────────────────────────────────

TRIVY_SERVER_URL = os.environ.get('TRIVY_SERVER_URL', 'http://localhost:4954')
REGISTRY_INTERNAL_URL = os.environ.get('REGISTRY_INTERNAL_URL', 'http://localhost:5000')
REGISTRY_STORAGE_PATH = os.environ.get('REGISTRY_STORAGE_PATH', '/var/lib/registry')

# ── Storage backend ───────────────────────────────────────────────────────────
# 'filesystem' (default) or 's3'
REGISTRY_STORAGE_BACKEND = os.environ.get('REGISTRY_STORAGE_BACKEND', 'filesystem')

# S3 / S3-compatible storage (used when REGISTRY_STORAGE_BACKEND=s3)
REGISTRY_S3_REGION         = os.environ.get('REGISTRY_S3_REGION', '')
REGISTRY_S3_BUCKET         = os.environ.get('REGISTRY_S3_BUCKET', '')
REGISTRY_S3_ACCESS_KEY     = os.environ.get('REGISTRY_S3_ACCESS_KEY', '')
REGISTRY_S3_SECRET_KEY     = os.environ.get('REGISTRY_S3_SECRET_KEY', '')
REGISTRY_S3_ENDPOINT          = os.environ.get('REGISTRY_S3_ENDPOINT', '')           # blank = AWS; set for MinIO/R2/etc.
REGISTRY_S3_ROOT_DIRECTORY    = os.environ.get('REGISTRY_S3_ROOT_DIRECTORY', '')     # optional key prefix
REGISTRY_S3_FORCE_PATH_STYLE  = os.environ.get('REGISTRY_S3_FORCE_PATH_STYLE', 'false')  # required for MinIO/R2
REGISTRY_S3_SECURE            = os.environ.get('REGISTRY_S3_SECURE', 'true')              # set false for HTTP-only MinIO
REGISTRY_S3_REDIRECT_ENDPOINT = os.environ.get('REGISTRY_S3_REDIRECT_ENDPOINT', '') # public URL for presigned redirects

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'registry': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}