# Generated by Django 6.0.6 on 2026-06-18 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('registry_type', models.CharField(choices=[('docker-hub', 'Docker Hub'), ('ghcr', 'GitHub Container Registry'), ('ecr', 'Amazon ECR'), ('gcr', 'Google Container Registry'), ('harbor', 'Harbor'), ('generic', 'Generic (OCI / Docker v2)')], default='generic', max_length=32)),
                ('endpoint', models.CharField(help_text='Base URL, e.g. https://registry.example.com', max_length=512)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_enc', models.TextField(blank=True, help_text='Stored credential (write-only in API)')),
                ('insecure', models.BooleanField(default=False, help_text='Skip TLS verification')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReplicationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('push', 'Push to remote'), ('pull', 'Pull from remote')], default='push', max_length=8)),
                ('source_filter', models.CharField(blank=True, help_text='Image name filter, e.g. library/**', max_length=512)),
                ('tag_filter', models.CharField(blank=True, help_text='Tag filter, e.g. v* or latest', max_length=255)),
                ('destination_namespace', models.CharField(blank=True, help_text='Override namespace on destination', max_length=255)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('on_push', 'On push'), ('scheduled', 'Scheduled')], default='manual', max_length=16)),
                ('schedule', models.CharField(blank=True, help_text='Cron expression when trigger=scheduled', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('delete_remote_on_local_delete', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_rules', to='registry.remoteregistry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex colour for UI display', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='registry.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
