# Generated by Django 6.0.6 on 2026-06-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auditlog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationrule',
            name='bandwidth_limit_kb',
            field=models.IntegerField(default=-1, help_text='Bandwidth cap in Kbps; -1 = unlimited'),
        ),
        migrations.AddField(
            model_name='replicationrule',
            name='flatten_mode',
            field=models.CharField(choices=[('none', 'No flattening'), ('flatten_1', 'Flatten 1 level'), ('flatten_all', 'Flatten all levels')], default='flatten_1', max_length=16),
        ),
        migrations.AddField(
            model_name='replicationrule',
            name='label_filter',
            field=models.CharField(blank=True, help_text='Comma-separated label matchers, e.g. env=prod', max_length=512),
        ),
        migrations.AddField(
            model_name='replicationrule',
            name='override_existing',
            field=models.BooleanField(default=True, help_text='Overwrite artifacts that already exist on destination'),
        ),
        migrations.AddField(
            model_name='replicationrule',
            name='resource_type',
            field=models.CharField(choices=[('all', 'All'), ('image', 'Image'), ('chart', 'Helm Chart'), ('artifact', 'OCI Artifact')], default='all', max_length=16),
        ),
        migrations.AddField(
            model_name='replicationrule',
            name='single_active',
            field=models.BooleanField(default=False, help_text='Allow only one active execution at a time'),
        ),
        migrations.AlterField(
            model_name='projectpolicy',
            name='prevent_vulnerable_images',
            field=models.BooleanField(default=False, help_text='Block pulls when the image violates the vuln_block_rules thresholds'),
        ),
        migrations.AlterField(
            model_name='remoteregistry',
            name='registry_type',
            field=models.CharField(choices=[('docker-hub', 'Docker Hub'), ('docker-registry', 'Docker Registry'), ('ghcr', 'GitHub Container Registry (GHCR)'), ('ecr', 'Amazon ECR'), ('gcr', 'Google Container Registry (GCR)'), ('acr-azure', 'Azure Container Registry (ACR)'), ('acr-alibaba', 'Alibaba Cloud Container Registry (ACR)'), ('tcr', 'Tencent Container Registry (TCR)'), ('swr', 'Huawei SWR'), ('harbor', 'Harbor'), ('jfrog', 'JFrog Artifactory'), ('generic', 'Generic (OCI / Docker v2)')], default='generic', max_length=32),
        ),
    ]
