# Generated by Django 6.0.6 on 2026-06-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_remove_acr_alibaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tags', to='registry.label'),
        ),
        migrations.CreateModel(
            name='ReplicationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('error', 'Error')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('copied', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, help_text='Append-only log lines from the task')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='registry.replicationrule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
