# Generated by Django 6.0.6 on 2026-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_sync_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=16)),
                ('triggered_by', models.CharField(default='schedule', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('orphans_deleted', models.IntegerField(default=0)),
                ('retention_deleted', models.IntegerField(default=0)),
                ('audit_deleted', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('blob_gc_ok', models.BooleanField(null=True)),
                ('blob_gc_output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vulnallowlistentry',
            unique_together={('project', 'tag', 'cve_id')},
        ),
    ]
