# Generated by Django 6.0.6 on 2026-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True)),
                ('oidc_enabled', models.BooleanField(default=False)),
                ('oidc_provider_type', models.CharField(blank=True, default='', max_length=64)),
                ('oidc_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('oidc_client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('oidc_server_url', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
