# Generated by Django 6.0.6 on 2026-06-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personal_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gc_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gc_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gc_last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
