# Generated by Django 6.0.6 on 2026-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_trivy_db_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gc_schedule_day_of_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gc_schedule_day_of_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gc_schedule_time',
            field=models.CharField(default='02:00', max_length=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gc_schedule_type',
            field=models.CharField(choices=[('hourly', 'Every hour'), ('every_n_hours', 'Every N hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
