# Generated by Django 6.0.6 on 2026-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_gc_schedule_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='job_log_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Delete GC, sync, replication, and Trivy update job rows older than this many days. 0 = keep forever.'),
        ),
    ]
